services:
  - type: web
    name: deepraj-mail-pro
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
