-- ============================================================
-- DEPRECATED: This file is an older, INCOMPLETE version of the schema.
--
-- The CANONICAL, PRODUCTION schema is at:
--   backend/src/db/schema.sql
--
-- The application's migration runner (backend/src/db/migrate.js) uses
-- ONLY the canonical schema file above. This file is never executed.
--
-- ISSUE-35 Fix: This file exists purely as a historical artifact.
-- TODO: Delete backend/schema.sql (this file) to avoid confusion.
-- ============================================================
-- See: backend/src/db/schema.sql for the up-to-date schema.
